/**
 * TheBreachLevel - Underground Hive Tunnels with Queen Boss Fight
 *
 * This module exports the level class and all supporting utilities.
 */

// Communications
export {
  COMMS_BOSS_DEATH,
  COMMS_BOSS_DETECTED,
  COMMS_BOSS_PHASE_2,
  COMMS_BOSS_PHASE_3,
  COMMS_LEVEL_START,
  NOTIFICATIONS,
  OBJECTIVES,
} from './comms';
// Constants
export {
  ACID_SPIT_PROJECTILE_SPEED,
  ACID_SPRAY_PROJECTILE_COUNT,
  ACID_SPRAY_SPEED,
  ACID_SPRAY_SPREAD_ANGLE,
  ARENA_PILLAR_COUNT,
  ARENA_PILLAR_HEIGHT,
  ARENA_PILLAR_RADIUS,
  COLORS,
  DAMAGE_INVINCIBILITY_MS,
  ENEMY_DETECTION_RANGE,
  ENEMY_STATS,
  GRENADE_COOLDOWN,
  GRENADE_MAX_DAMAGE,
  GRENADE_RADIUS,
  GROUND_POUND_INDICATOR_DURATION,
  INVINCIBILITY_SCALING,
  MELEE_COOLDOWN,
  MELEE_DAMAGE,
  MELEE_RANGE,
  PLAYER_MAX_HEALTH,
  QUEEN_ATTACK_DAMAGE,
  QUEEN_ATTACK_RANGE,
  QUEEN_ATTACK_TELEGRAPH,
  QUEEN_CHARGE_RADIUS,
  QUEEN_CHARGE_RETURN_TIME,
  QUEEN_CHARGE_SPEED,
  QUEEN_COOLDOWN_SCALING,
  QUEEN_DAMAGE_SCALING,
  QUEEN_DEATH_SLOWMO_DURATION,
  QUEEN_DEATH_SLOWMO_SCALE,
  QUEEN_DEATH_THROES_SPAWN_INTERVAL,
  QUEEN_DEATH_THROES_THRESHOLD,
  QUEEN_EGG_BURST_SPAWN_COUNT,
  QUEEN_FRENZY_ATTACK_COUNT,
  QUEEN_FRENZY_ATTACK_DELAY,
  QUEEN_HEALTH_SCALING,
  QUEEN_MAX_HEALTH,
  QUEEN_PHASE_2_THRESHOLD,
  QUEEN_PHASE_3_THRESHOLD,
  // New phase-based attack system constants
  QUEEN_PHASE_COOLDOWNS,
  QUEEN_PHASE_TRANSITION_DURATION,
  QUEEN_POISON_CLOUD_DURATION,
  QUEEN_POISON_CLOUD_RADIUS,
  QUEEN_SCREECH_SPAWN_COUNT,
  QUEEN_SCREECH_STUN_DURATION,
  QUEEN_STAGGER_DURATION,
  QUEEN_WEAK_POINT_GLOW,
  QUEEN_WEAK_POINT_HEALTH,
  QUEEN_WEAK_POINT_MULTIPLIERS,
  SCAN_COOLDOWN_SCALING,
  STARTING_GRENADES,
  TUNNEL_DIAMETER,
  TUNNEL_SEGMENT_LENGTH,
  WEAK_POINT_COOLDOWN,
  WEAK_POINT_COOLDOWN_BASE,
  WEAK_POINT_DAMAGE_MULTIPLIER,
  WEAK_POINT_DURATION,
  WEAK_POINT_DURATION_BASE,
  WEAK_POINT_DURATION_SCALING,
  WEAK_POINT_MAX_ALPHA,
  WEAK_POINT_MIN_ALPHA,
  WEAK_POINT_PULSE_SPEED,
} from './constants';
// Enemies
export {
  checkEnemyHit,
  damageEnemy,
  disposeEnemies,
  getEnemyAttackDamage,
  getInitialSpawnConfig,
  spawnEnemy,
  updateEnemyAI,
} from './enemies';
export type { HiveStructurePlacement, PlacedAsset } from './environment';
// Environment
export {
  disposeBreachAssets,
  HIVE_STRUCTURE_PLACEMENTS,
  HiveEnvironmentBuilder,
  loadBreachAssets,
  placeBreachAssets,
  updateBiolights,
} from './environment';
// Hazards
export {
  checkAcidPoolDamage,
  checkEggClusterTrigger,
  checkPheromoneCloud,
  HazardBuilder,
} from './hazards';
export type { QueenEventType } from './queen';
// Queen Boss
export {
  activateDeathThroes,
  animateAcidSpit,
  animateAcidSpray,
  animateCharge,
  // Legacy exports for backwards compatibility
  animateClawSwipe,
  animateEggBurst,
  animateFrenzyAttack,
  animateGroundPound,
  animatePhaseTransition,
  animatePoisonCloud,
  animateQueen,
  animateQueenAwakening,
  animateQueenDeath,
  animateScreech,
  animateTailSlam,
  animateTailSwipe,
  calculateQueenDamage,
  checkChargeCollision,
  checkPoisonCloudCollision,
  checkWeakPointHit,
  createQueen,
  damageWeakPoint,
  disposeQueen,
  getAcidSprayPositions,
  getAvailableAttacks,
  getEggBurstSpawnPositions,
  getPhaseAttackCooldown,
  getPhaseMultiplier,
  getQueenPhase,
  getScaledCooldown,
  getScaledQueenDamage,
  getScaledQueenHealth,
  getSpawnCooldown,
  getSpawnCount,
  getSpawnType,
  hideWeakPoints,
  preloadQueenModels,
  revealWeakPoints,
  // New attack system exports
  selectNextAttack,
  setQueenDifficulty,
  shouldEnterDeathThroes,
  startFrenzy,
  updateQueenAI,
} from './queen';
// Main level class
export { TheBreachLevel } from './TheBreachLevel';
// Types
export type {
  AcidPool,
  BioluminescentLight,
  CapturedVehicle,
  EggCluster,
  Enemy,
  EnemyState,
  EnemyStats,
  EnemyType,
  HiveStructure,
  HiveZone,
  LegacyQueenAttackType,
  LevelPhase,
  PheromoneCloud,
  Queen,
  QueenAIState,
  QueenAttackType,
  QueenBodyParts,
  QueenPhase,
  // New types for enhanced boss system
  QueenWeakPoint,
  QueenWeakPointId,
  TunnelSegment,
} from './types';
